### ISSUE TITLE
 Promise rejection was handled asynchronously

### ISSUE THREAD

**Issue by nicubarbaros** [timberio/timber-js#67] opened 2019-08-23 12:22 UTC
So thats what happened for us today. 
It started to happen right when we hit our limit and we had to pay more to increase the limit.

Suddenly all of our server cpu where on maximum capacity, crashed at some point and our server logged: `PromiseRejectionHandledWarning: Promise rejection was handled asynchronously`

```
"@timberio/node": "^0.34.1",
"@timberio/winston": "^0.34.1",
```
We use integration with `Winston` https://docs.timber.io/setup/languages/javascript/integrations/winston . Its exactly like in doc. 

CPU leak does not happen anymore if we remove timber.

**Comment by nicubarbaros** [comment] 2019-08-23 12:39
Referencing  #43

**Comment by leebenson** [comment] 2019-08-23 12:53
Thanks for reporting this, @nicubarbaros.

You mentioned hitting a limit -- are you talking about a Timber.io account limit? Or a limit with another provider? If it's the former, it could simply be that a call to `.log()` is failing due with a non-200 status code because of not accepting the logs due to the account limit, which is then rejecting the Promise. If it's the latter, that would be useful to know, too, so we can try to recreate the scenario on our end and test it.

Are you able to share some code so I could help diagnose this for you, please?

I'm specifically interested to see how you're calling `logger.log()`, and whether you're wrapping that in a try-catch block, such as the examples referenced at https://github.com/timberio/timber-js/issues/43#issuecomment-471179715 -- or if you're ignoring exceptions per that same comment.

Let me know and I'll get this looked at as a priority. Thanks!

**Comment by nicubarbaros** [comment] 2019-08-23 13:39
@leebenson it's a Timber.io account limit. 

We don't use `logger.log()`, but `logger.info()`, `logger.debug()`, `logger.error`  and we do not catch as mentioned on #43, which is maybe our bad. 

The logger is pretty straightforward as on documentations

```
const timber = new Timber(apiKey,sourceId);

const logger = createLogger({
  level: 'debug',
  transports: [new TimberTransporter(timber)],
});
```

We also pass a secondary `transporter` which is `WinstonElasticsearch` (not sure if this belongs to the error, but if needed I will gladly provide the `winstonElasticSearchTransport` configuration.

Logger usage

```
logger.info('Scheduled posts: Job done', msg);
```

I hope that helps and any other information required I can pass along please tell me.

**Comment by leebenson** [comment] 2019-08-23 14:33
Got it, thanks. This is helpful.

By design, all the `log|info|warn()` etc methods return Promises, so that client code can determine whether a log has been successfully delivered.

This provides flexibility for deciding what to do with failures. In some apps (or parts of an app), a developer may want logs to just be 'fire and forgot' -- they don't mind if the occasional log line doesn't make it, or they don't want to do anything particular with failures.

There are a couple of ways to handle that scenario:

**1. Wrap the log in try/catch or add a `.catch()` block**

Something like:

```ts
// Within an async function
try {
  await logger.info("some log")
} catch (_) {
  // Intentionally blank... we'll just ignore all errors
}
```

Or...

```ts
logger.info("some log").catch(e => {
  // Maybe we just want to log to stdout
  console.log(`something happened: ${e}`)
})
```

**2. Ignore _all_ Timber exceptions, globally**

The nuclear option, if you don't mind suppressing _all_ errors, is to ignore them at a library level:

```ts
const timber = new Timber("your-api-key", {
    ignoreExceptions: true
});
```

This should prevent _all_ calls to logging from surfacing requested Promises, so you won't need to do anything explicit to catch them.

---

By default, we don't suppress exceptions because we assume that developers want to know about errors, and handle them explicitly.

Let me know if this doesn't fix your use-case, and I'll look into it further.

Otherwise, if you're happy for me to close this for now, you're always welcome to open a new issue if you run into anything else.

**Comment by nicubarbaros** [comment] 2019-08-23 14:43
Thank you for your detailed response @leebenson. 
You can close it for now. 

Have a great day.

**Closed as completed** 2019-08-24 04:56 UTC
